/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : ResourceStatus,
  'paymentMethod' : PaymentMethod,
  'farmerId' : Principal,
  'resourceId' : bigint,
  'createdAt' : bigint,
  'bookingDate' : string,
}
export interface CropPrice {
  'marketName' : string,
  'pricePerQuintal' : number,
  'date' : string,
  'unit' : string,
  'cropName' : string,
}
export type PaymentMethod = { 'offline_cash' : null } |
  { 'online_upi' : null };
export interface Resource {
  'id' : bigint,
  'locationLat' : number,
  'locationLng' : number,
  'ownerName' : string,
  'isAvailable' : boolean,
  'description' : string,
  'pricePerDay' : number,
  'distanceKm' : [] | [number],
  'resourceType' : ResourceType,
}
export type ResourceStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type ResourceType = { 'labour' : null } |
  { 'tractor' : null } |
  { 'drone' : null };
export interface UserProfile {
  'locationLat' : number,
  'locationLng' : number,
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeatherData {
  'temperature' : number,
  'date' : string,
  'windSpeed' : number,
  'humidity' : number,
  'rainfall' : number,
  'condition' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResource' : ActorMethod<[Resource], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint, string, PaymentMethod], Booking>,
  'getAllCropPrices' : ActorMethod<[], Array<CropPrice>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCropPrice' : ActorMethod<[string, string], CropPrice>,
  'getFarmerBookings' : ActorMethod<[], Array<Booking>>,
  'getResourceAvailability' : ActorMethod<[bigint, string], boolean>,
  'getResourcesByType' : ActorMethod<[ResourceType], Array<Resource>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeatherData' : ActorMethod<[string], WeatherData>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCropPrice' : ActorMethod<[CropPrice], undefined>,
  'setWeatherData' : ActorMethod<[WeatherData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];