/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceType = IDL.Variant({
  'labour' : IDL.Null,
  'tractor' : IDL.Null,
  'drone' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'ownerName' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'pricePerDay' : IDL.Float64,
  'distanceKm' : IDL.Opt(IDL.Float64),
  'resourceType' : ResourceType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'offline_cash' : IDL.Null,
  'online_upi' : IDL.Null,
});
export const ResourceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : ResourceStatus,
  'paymentMethod' : PaymentMethod,
  'farmerId' : IDL.Principal,
  'resourceId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'bookingDate' : IDL.Text,
});
export const CropPrice = IDL.Record({
  'marketName' : IDL.Text,
  'pricePerQuintal' : IDL.Float64,
  'date' : IDL.Text,
  'unit' : IDL.Text,
  'cropName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'locationLat' : IDL.Float64,
  'locationLng' : IDL.Float64,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'date' : IDL.Text,
  'windSpeed' : IDL.Float64,
  'humidity' : IDL.Float64,
  'rainfall' : IDL.Float64,
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResource' : IDL.Func([Resource], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func([IDL.Nat, IDL.Text, PaymentMethod], [Booking], []),
  'getAllCropPrices' : IDL.Func([], [IDL.Vec(CropPrice)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropPrice' : IDL.Func([IDL.Text, IDL.Text], [CropPrice], ['query']),
  'getFarmerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getResourceAvailability' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'getResourcesByType' : IDL.Func(
      [ResourceType],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func([IDL.Text], [WeatherData], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCropPrice' : IDL.Func([CropPrice], [], []),
  'setWeatherData' : IDL.Func([WeatherData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceType = IDL.Variant({
    'labour' : IDL.Null,
    'tractor' : IDL.Null,
    'drone' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'ownerName' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'pricePerDay' : IDL.Float64,
    'distanceKm' : IDL.Opt(IDL.Float64),
    'resourceType' : ResourceType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'offline_cash' : IDL.Null,
    'online_upi' : IDL.Null,
  });
  const ResourceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : ResourceStatus,
    'paymentMethod' : PaymentMethod,
    'farmerId' : IDL.Principal,
    'resourceId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'bookingDate' : IDL.Text,
  });
  const CropPrice = IDL.Record({
    'marketName' : IDL.Text,
    'pricePerQuintal' : IDL.Float64,
    'date' : IDL.Text,
    'unit' : IDL.Text,
    'cropName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'locationLat' : IDL.Float64,
    'locationLng' : IDL.Float64,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'date' : IDL.Text,
    'windSpeed' : IDL.Float64,
    'humidity' : IDL.Float64,
    'rainfall' : IDL.Float64,
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResource' : IDL.Func([Resource], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, PaymentMethod],
        [Booking],
        [],
      ),
    'getAllCropPrices' : IDL.Func([], [IDL.Vec(CropPrice)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropPrice' : IDL.Func([IDL.Text, IDL.Text], [CropPrice], ['query']),
    'getFarmerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getResourceAvailability' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'getResourcesByType' : IDL.Func(
        [ResourceType],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func([IDL.Text], [WeatherData], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCropPrice' : IDL.Func([CropPrice], [], []),
    'setWeatherData' : IDL.Func([WeatherData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };